apiVersion: apps/v1
kind: Deployment
metadata:
  name: dpc
  labels:
    app: dpc
spec:
  replicas: 2
  selector:
    matchLabels:
      app: dpc
  template:
    metadata:
      labels:
        app: dpc
    spec:
      containers:
      - name: dpc-container
        image: gcr.io/rosy-spring-327701/dpc:v2
        ports:
        - containerPort: 8080
          name: http
          protocol: TCP
